port: 7890
socks-port: 7891
allow-lan: true
mode: rule
log-level: info
external-controller: 127.0.0.1:9090

dns:
  enable: true
  listen: 0.0.0.0:53
  nameserver:
    - 178.22.122.100
    - 185.51.200.2

proxies:
  - name: "Shecandns"
    type: vmess
    server: "free.shecan.ir"
    port: 443
    tls: true
proxy-groups:
  - name: "Auto"
    type: select
    proxies:
      - Shecandns

rules:
  - DOMAIN-SUFFIX,warframe.com,Auto
  - DOMAIN,chat.warframe.com,Auto
  - IP-CIDR,35.190.0.0/16,Auto
  - IP-CIDR,172.217.0.0/16,Auto
  - DST-PORT,6695,Auto
  - DST-PORT,6696,Auto
  - DST-PORT,6697,Auto
  - DST-PORT,6698,Auto
  - DST-PORT,6699,Auto
  - MATCH,Auto
